on:
  workflow_dispatch:
    inputs:
      MANIFEST_BRANCH:
        description: 'OrangeFox for ASUS Zenfone with LineageOS'
        required: true
        default: '12.1'
        type: choice
        options:
        - 14.1
        - 12.1
        - 11.0
